export { default as EditEducationalProgramModal } from './EditEducationalProgramModal';
export * from './EditEducationalProgramModal';
export { default as AddEducationalProgramModal } from './AddEducationalProgramModal';
export * from './AddEducationalProgramModal';
export { default as AcademicDegree } from './AcademicDegree';
export * from './AcademicDegree';
export { default as StudyFormat } from './StudyFormat';
export * from './StudyFormat';
export { default as EducationalProgramsTable } from './EducationalProgramsTable';
export * from './EducationalProgramsTable';
export { default as EditSpecialtyModal } from './EditSpecialtyModal';
export * from './EditStudyFieldModal';
export { default as AddSpecialtyModal } from './AddSpecialtyModal';
export * from './AddSpecialtyModal';
export { default as EditStudyFieldModal } from './EditStudyFieldModal';
export * from './EditStudyFieldModal';
export { default as AddStudyFieldModal } from './AddStudyFieldModal';
export * from './AddStudyFieldModal';
