export const APP_ROUTES = Object.freeze({
  HOME: '/home',
  STUDENTS: '/students',
  STUDENT_GROUPS: '/student-groups',
  LECTURERS: '/lecturers',
  SUBJECTS: '/subjects',
  ROOMS: '/rooms',
  EDUCATIONAL_PROGRAMS: '/educational-programs',
  DEPARTMENTS: '/departments',
  EDUCATIONAL_COURSES: '/educational-courses',
  TIMETABLES: '/timetables',
  HELP: '/help',
  LOGIN: '/login',
  FORGOT_PASSWORD: '/forgot-password',
  CHANGE_PASSWORD: '/change-password',
});
